### ISSUE TITLE
Battery icon showing lower battery level than it actually is

### ISSUE THREAD

**Issue by chrizz** [actuallymentor/battery#134]
I've noticed that when battery charge drops somewhere below 50%, the menu bar icon actually shows an almost empty battery. This happens suddenly. When battery level is 50-60 or above the icon shows a more accurate charge state.

Using v1.1.4 with 80% charge limit enabled on a Macbook Pro 14 M2 Pro.

<img width="295" alt="Skärmavbild 2023-04-26 kl  21 33 42" src="https://user-images.githubusercontent.com/249693/234683718-1ec4aefd-722a-4946-a507-62f5279626c0.png">

**Comment by earthsound** [comment]
This was fixed with GH-119 which was merged 3/26, after the last release.

**Comment by kristiankruse** [comment]
Same issue is still on 1.1.4
<img width="388" alt="screenshot 2023-05-04 at 12 54 40" src="https://user-images.githubusercontent.com/564745/236315297-664285f0-67c9-4e76-8929-129fb3b96c44.png">

**Comment by actuallymentor** [comment]
Should be fixed in v1.1.5 (releasing in 5 min), reopen if it persists please :)
